project:
  type: website

website:
  title: "DS Labs"
  site-url: "https://ds-labs.carloscamara.es/"
  description:  "A lab for experimenting with Data Science and Data visualisation"
  # twitter-card: true
  # open-graph: true
  navbar:
    right:
      - blog.qmd
      - about.qmd
      - icon: github
        href: https://github.com/ccamara
      - icon: mastodon
        href: https://scholar.social/users/ccamara
      - icon: instagram
        href: https://pixelfed.social/datasaurus
  comments: 
    hypothesis:
      theme: clean
      openSidebar: false
    giscus:
      repo: ccamara/dslabs
      category: Comments 
      category-id: DIC_kwDOJFtHLs4CUtWF
      mapping: pathname
      input-position: top
  google-analytics:  
    tracking-id: "G-GM3K1FXK2H"
    storage: none
format:
  html:
    theme: journal #sandstone or pulse are also good
    css: styles.css

editor: visual

