project:
  type: website

website:
  title: "DS Labs"
  description:  "A lab for experimenting with Data Science and Data visualisation"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/ccamara
      - icon: mastodon
        href: https://scholar.social/users/ccamara
format:
  html:
    theme: journal
    css: styles.css

editor: visual

