name: dslabs
channels:
  - conda-forge
  - defaults
dependencies:
  - altair
  - geopandas
  - jupyter
  - nbclient
  - nbformat
  - pandas
  - pip
  - python
  - pyyaml
  - vega_datasets
  - pip:
    - sparqlwrapper
 